### ISSUE TITLE
Can't compile on linux

### ISSUE THREAD

**Issue by racerxdl** [quiet/libcorrect#1]
It seens that one folder is missing in the repository. Using cmake, I get this problem:

> :~/libcorrect/build$ cmake ..
> -- The C compiler identification is GNU 5.4.0
> -- The CXX compiler identification is GNU 5.4.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Looking for dotprod in FEC
> -- Looking for dotprod in FEC - not found
> -- Looking for include file x86intrin.h
> -- Looking for include file x86intrin.h - found
> CMake Error at CMakeLists.txt:56 (add_subdirectory):
>   add_subdirectory given source "benchmarks" which is not an existing
>   directory.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/teske/libcorrect/build/CMakeFiles/CMakeOutput.log".
> See also "/home/teske/libcorrect/build/CMakeFiles/CMakeError.log".
>

**Comment by brian-armstrong** [comment]
Thanks for trying out libcorrect :)

That's embarrassing - I previously commented out the CMake rule to build this subdirectory, but I accidentally added it in later. I just pushed a new commit to comment it back out, which should resolve this build issue.

Eventually I'll actually check in the benchmarks, but they're not quite ready yet, and it hasn't been a high priority. (Good news is, the portable code for libcorrect appears to be about as performant as libfec :))

**Comment by racerxdl** [comment]
It resolved :D yey
