### ISSUE TITLE
memory leak in RS decoding

### ISSUE THREAD

**Issue by piotrszulcaptiv** [quiet/libcorrect#14]
Hi,
My colleague has found a memory leak in the RS decoder. You do malloc(), but never call free().
I suggest that you take a look if the the same problem exists in your other decoders.

Piotr Szulc

**Comment by brian-armstrong** [comment]
Thanks for the report. I went ahead and fixed those leaks. I had previously run valgrind on my tests but this involved a more recent section of code that hadn't been run under valgrind.
